
package nmb.transakcije;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransakcijeWSDLService", targetNamespace = "http://transakcije.nmb/", wsdlLocation = "http://localhost:8080/SpletnaBankaWSDL/TransakcijeWSDL?wsdl")
public class TransakcijeWSDLService
    extends Service
{

    private final static URL TRANSAKCIJEWSDLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSAKCIJEWSDLSERVICE_EXCEPTION;
    private final static QName TRANSAKCIJEWSDLSERVICE_QNAME = new QName("http://transakcije.nmb/", "TransakcijeWSDLService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SpletnaBankaWSDL/TransakcijeWSDL?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSAKCIJEWSDLSERVICE_WSDL_LOCATION = url;
        TRANSAKCIJEWSDLSERVICE_EXCEPTION = e;
    }

    public TransakcijeWSDLService() {
        super(__getWsdlLocation(), TRANSAKCIJEWSDLSERVICE_QNAME);
    }

    public TransakcijeWSDLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSAKCIJEWSDLSERVICE_QNAME, features);
    }

    public TransakcijeWSDLService(URL wsdlLocation) {
        super(wsdlLocation, TRANSAKCIJEWSDLSERVICE_QNAME);
    }

    public TransakcijeWSDLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSAKCIJEWSDLSERVICE_QNAME, features);
    }

    public TransakcijeWSDLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransakcijeWSDLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransakcijeWSDL
     */
    @WebEndpoint(name = "TransakcijeWSDLPort")
    public TransakcijeWSDL getTransakcijeWSDLPort() {
        return super.getPort(new QName("http://transakcije.nmb/", "TransakcijeWSDLPort"), TransakcijeWSDL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransakcijeWSDL
     */
    @WebEndpoint(name = "TransakcijeWSDLPort")
    public TransakcijeWSDL getTransakcijeWSDLPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://transakcije.nmb/", "TransakcijeWSDLPort"), TransakcijeWSDL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSAKCIJEWSDLSERVICE_EXCEPTION!= null) {
            throw TRANSAKCIJEWSDLSERVICE_EXCEPTION;
        }
        return TRANSAKCIJEWSDLSERVICE_WSDL_LOCATION;
    }

}
